# Este archivo es un ejemplo de un archivo docker-compose.yml para ejecutar Tomcat 10.1 con una aplicación web en el contenedor.
# También incluye un contenedor de base de datos MySQL. Puedes personalizarlo según tus necesidades.
# Asegúrate de tener Docker y Docker Compose instalados en tu máquina antes de ejecutar este archivo.

services:
  tomcat:
    image: docker.io/bitnami/tomcat:10.1
    ports:
      - '8080:8080'
    volumes:
      - './mi_carpeta_local:/bitnami/tomcat/webapps/ROOT'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=root
  mysql:
    image: docker.io/bitnami/mysql:8.4
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  tomcat_data:
    driver: local
  mysql_data:
    driver: local 
   
