DROP DATABASE IF EXISTS evento;
CREATE DATABASE evento CHARACTER SET utf8mb4;
USE evento;

CREATE TABLE categoria (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(300)
);
CREATE TABLE evento (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(300),
  lugar VARCHAR(150) NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  id_categoria INT UNSIGNED ,
  FOREIGN KEY (id_categoria) REFERENCES categoria(id) ON DELETE SET NULL
);
CREATE TABLE persona(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido1 VARCHAR(100) NOT NULL,
    apellido2 VARCHAR(100) NOT NULL,
	tipo ENUM('Participante', 'Artista') NOT NULL
);

CREATE TABLE persona_evento (
    id_persona INT UNSIGNED NOT NULL,
    id_evento INT UNSIGNED NOT NULL,
    fecha DATE NOT NULL,
    PRIMARY KEY (id_persona, id_evento), -- Composite primary key
    FOREIGN KEY (id_persona) REFERENCES persona(id) ON DELETE CASCADE,
    FOREIGN KEY (id_evento) REFERENCES evento(id) ON DELETE CASCADE
);

CREATE TABLE participante (
  id_persona INT UNSIGNED PRIMARY KEY,
  email VARCHAR(150) NOT NULL UNIQUE,
  FOREIGN KEY (id_persona) REFERENCES persona(id) ON DELETE CASCADE
);


CREATE TABLE artista (
  id_persona INT UNSIGNED PRIMARY KEY,
  fotografia VARCHAR(255),
  obra_destacada VARCHAR(255),
  FOREIGN KEY (id_persona) REFERENCES persona(id) ON DELETE CASCADE
);
INSERT INTO categoria (nombre, descripcion) VALUES
('Música', 'Eventos relacionados con la música'),
('Arte', 'Eventos culturales y artísticos'),
('Deportes', 'Competiciones deportivas y recreativas'),
('Tecnología', 'Eventos sobre innovación tecnológica'),
('Ciencia', 'Conferencias científicas y académicas'),
('Cine', 'Festivales de cine y cineastas'),
('Literatura', 'Eventos de literatura y autores'),
('Gastronomía', 'Eventos relacionados con la comida y la cocina'),
('Moda', 'Desfiles y eventos de moda'),
('Turismo', 'Eventos relacionados con el turismo y viajes'),
('Teatro', 'Obras y espectáculos teatrales'),
('Conferencias', 'Conferencias sobre temas de interés general'),
('Energía', 'Eventos sobre energías renovables y sustentabilidad'),
('Música Electrónica', 'Eventos relacionados con la música electrónica'),
('Diseño', 'Eventos sobre diseño gráfico y de producto'),
('Fotografía', 'Eventos sobre fotografía y artes visuales'),
('Arqueología', 'Exposiciones arqueológicas y descubrimientos'),
('Filosofía', 'Eventos de discusión filosófica y reflexión'),
('Educación', 'Congresos sobre métodos educativos'),
('Medioambiente', 'Eventos enfocados en la conservación ambiental'),
('Comedia', 'Eventos y espectáculos de comedia'),
('Futuro', 'Eventos sobre el futuro de la humanidad'),
('Gestión Empresarial', 'Eventos sobre administración y negocios'),
('Salud', 'Conferencias sobre salud y bienestar'),
('Literatura Infantil', 'Eventos literarios para niños'),
('Ballet', 'Espectáculos de ballet y danza clásica'),
('Innovación Social', 'Proyectos que transforman la sociedad'),
('Negocios Internacionales', 'Eventos sobre comercio internacional'),
('Programación', 'Cursos y talleres de programación'),
('Blockchain', 'Eventos sobre criptomonedas y blockchain'),
('Marketing', 'Eventos sobre marketing digital y tradicional'),
('Gaming', 'Competiciones y eventos de videojuegos'),
('Cultura Popular', 'Eventos sobre cultura pop y entretenimiento'),
('Bienestar', 'Eventos relacionados con la salud mental y física'),
('Diseño de Moda', 'Eventos de diseño y tendencias en la moda'),
('Comida Gourmet', 'Exposición sobre comida gourmet y de alta cocina'),
('Ingeniería', 'Congresos y exposiciones sobre ingeniería'),
('Desarrollo Sostenible', 'Eventos enfocados en la sostenibilidad'),
('Educación Ambiental', 'Cursos y conferencias sobre medioambiente'),
('Negocios Locales', 'Eventos sobre negocios y emprendimiento local'),
('Viajes', 'Ferias de viajes y turismo'),
('Cine Experimental', 'Eventos y festivales de cine experimental'),
('Cultura Digital', 'Eventos sobre el impacto de la tecnología'),
('Fotografía Digital', 'Exposiciones sobre fotografía digital'),
('Agricultura', 'Eventos y ferias sobre agricultura y tecnología'),
('Cine Documental', 'Festivales de cine documental'),
('Automóviles', 'Eventos relacionados con el mundo automotriz'),
('Ciencia y Tecnología', 'Eventos sobre avances científicos y tecnológicos'),
('Educación Superior', 'Congresos para estudiantes y académicos'),
('Mujeres en la Ciencia', 'Eventos y conferencias sobre mujeres en la ciencia'),
('Bienestar Social', 'Eventos sobre bienestar y trabajo social'),
('Arte Digital', 'Exposiciones y talleres sobre arte digital');

INSERT INTO evento (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES
('Concierto de Rock', 'Un gran concierto de rock en vivo', 'Estadio Nacional', '2025-05-01', '2025-05-01', 1),
('Exposición de Arte Moderno', 'Exposición de artistas contemporáneos', 'Museo de Arte', '2025-06-10', '2025-06-20', 2),
('Maratón Internacional', 'Competencia de correr a nivel internacional', 'Parque Central', '2025-07-15', '2025-07-15', 3),
('Congreso de Innovación Tecnológica', 'Evento de tecnología y startups', 'Centro de Convenciones', '2025-08-05', '2025-08-06', 4),
('Conferencia de Inteligencia Artificial', 'Conferencia sobre IA y sus aplicaciones', 'Universidad XYZ', '2025-09-12', '2025-09-12', 4),
('Feria de Ciencias', 'Exposición científica y de investigación', 'Auditorio Principal', '2025-10-01', '2025-10-01', 5),
('Festival de Cine Independiente', 'Proyección de cine independiente', 'Cine Centro', '2025-11-01', '2025-11-07', 6),
('Encuentro Literario', 'Reunión de escritores y lectores', 'Biblioteca Nacional', '2025-12-15', '2025-12-16', 7),
('Festival Gastronómico', 'Muestra de cocina internacional', 'Plaza Mayor', '2025-06-20', '2025-06-22', 8),
('Semana de la Moda', 'Desfile y presentación de nuevas colecciones', 'Centro de Moda', '2025-09-20', '2025-09-24', 9),
('Teatro Nacional', 'Espectáculo de teatro contemporáneo', 'Teatro Nacional', '2025-05-10', '2025-05-15', 10),
('Congreso Educativo', 'Congreso internacional de métodos educativos', 'Auditorio de la Universidad', '2025-06-01', '2025-06-05', 11),
('Conferencia de Energías Renovables', 'Explorando nuevas energías renovables', 'Centro de Convenciones', '2025-07-01', '2025-07-02', 12),
('Festival de Música Electrónica', 'Evento de música electrónica en vivo', 'Parque Central', '2025-08-15', '2025-08-15', 13),
('Expo Diseño Creativo', 'Exposición sobre diseño creativo y arquitectura', 'Centro de Exposiciones', '2025-09-10', '2025-09-12', 14),
('Cine de Autor', 'Festival de cine de autor', 'Cine Arte', '2025-10-10', '2025-10-15', 6),
('Arqueología Viva', 'Exposición sobre arqueología y descubrimientos', 'Museo Arqueológico', '2025-11-01', '2025-11-10', 15),
('Filosofía Contemporánea', 'Conferencia sobre filosofía moderna', 'Universidad ABC', '2025-12-01', '2025-12-02', 16),
('Festival de la Ciencia', 'Muestra de investigaciones científicas', 'Auditorio de Ciencias', '2025-01-05', '2025-01-10', 5),
('Bienestar y Salud', 'Conferencias sobre bienestar personal', 'Centro de Bienestar', '2025-02-15', '2025-02-18', 17),
('Diseño y Moda', 'Presentación de nuevas colecciones de moda', 'Centro de Diseño', '2025-03-01', '2025-03-05', 18),
('Festival Gastronómico Internacional', 'Evento de comida gourmet de todo el mundo', 'Plaza Mayor', '2025-04-10', '2025-04-12', 8),
('Bienestar Mental', 'Encuentro sobre salud mental y psicología', 'Centro de Psicología', '2025-05-20', '2025-05-22', 17),
('Festival Internacional de Cine', 'Muestra de cine de varios países', 'Cine El Paraíso', '2025-06-05', '2025-06-12', 6),
('Revolución Digital', 'Evento sobre las últimas tecnologías digitales', 'Auditorio Tecnológico', '2025-07-05', '2025-07-06', 4),
('Encuentro de Fotografía', 'Exposición de fotografía de artistas internacionales', 'Museo de Arte', '2025-08-10', '2025-08-15', 14),
('Arte y Cultura', 'Muestra de arte contemporáneo', 'Centro Cultural', '2025-09-01', '2025-09-05', 2),
('Festival de Danza', 'Presentación de danzas internacionales', 'Teatro Nacional', '2025-10-01', '2025-10-05', 10),
('Programación en Vivo', 'Talleres de programación y desarrollo de software', 'Centro de Innovación', '2025-11-01', '2025-11-03', 4),
('Concierto Clásico', 'Concierto de música clásica en vivo', 'Auditorio Principal', '2025-12-10', '2025-12-10', 1),
('Torneo de Videojuegos', 'Competencia de videojuegos en línea', 'Centro de Gaming', '2025-06-10', '2025-06-12', 19),
('Festivales Internacionales de Cine', 'Muestra de cine independiente internacional', 'Cine Mundo', '2025-05-10', '2025-05-15', 6),
('Exposición de Tecnología Futurista', 'Exposición sobre avances tecnológicos', 'Centro Tecnológico', '2025-04-10', '2025-04-12', 4),
('Encuentro de Empresarios', 'Evento de networking y negocios', 'Centro de Eventos', '2025-06-25', '2025-06-26', 20);

INSERT INTO persona (nombre, apellido1, apellido2, tipo) VALUES
('Carlos', 'Pérez', 'Gómez', 'Participante'),
('Ana', 'Martínez', 'López', 'Artista'),
('Luis', 'Rodríguez', 'Sánchez', 'Participante'),
('Maria', 'González', 'Vargas', 'Artista'),
('José', 'Ramírez', 'Hernández', 'Participante'),
('Laura', 'Díaz', 'Castro', 'Artista'),
('Juan', 'Torres', 'Morales', 'Participante'),
('Patricia', 'Fernández', 'Alonso', 'Artista'),
('Miguel', 'Martínez', 'Pérez', 'Participante'),
('Pedro', 'Sánchez', 'Ruiz', 'Artista'),
('Mónica', 'Gómez', 'Reyes', 'Participante'),
('Sofia', 'Hernández', 'López', 'Artista'),
('Andrés', 'Jiménez', 'Martín', 'Participante'),
('Elena', 'Pérez', 'Jiménez', 'Artista'),
('Carlos', 'Hernández', 'López', 'Participante'),
('Ana', 'Moreno', 'González', 'Artista'),
('David', 'Rodríguez', 'Fernández', 'Participante'),
('Lucía', 'Fernández', 'García', 'Artista'),
('Javier', 'Sánchez', 'Ruiz', 'Participante'),
('Raquel', 'Torres', 'Hernández', 'Artista'),
('Francisco', 'González', 'Martín', 'Participante'),
('María', 'Álvarez', 'González', 'Artista'),
('Luis', 'Rodríguez', 'Pérez', 'Participante'),
('Sandra', 'Mora', 'Torres', 'Artista'),
('Jorge', 'Jiménez', 'Pérez', 'Participante'),
('Carmen', 'Vargas', 'Rodríguez', 'Artista'),
('Antonio', 'Gómez', 'Hernández', 'Participante'),
('Patricia', 'Martínez', 'Sánchez', 'Artista'),
('Carlos', 'Martín', 'García', 'Participante'),
('Esther', 'Ramírez', 'Hernández', 'Artista'),
('Fernando', 'Sánchez', 'Pérez', 'Participante'),
('Ingrid', 'González', 'Reyes', 'Artista'),
('Raúl', 'Vázquez', 'Morales', 'Participante'),
('Lidia', 'López', 'Martínez', 'Artista'),
('Ramón', 'Pérez', 'Rodríguez', 'Participante'),
('Marta', 'García', 'Torres', 'Artista'),
('Manuel', 'Jiménez', 'Ramírez', 'Participante'),
('Verónica', 'Moreno', 'Sánchez', 'Artista'),
('Sergio', 'Torres', 'Morales', 'Participante'),
('Silvia', 'Álvarez', 'González', 'Artista'),
('Raúl', 'Sánchez', 'Torres', 'Participante'),
('Isabel', 'Martínez', 'González', 'Artista'),
('Pablo', 'Vázquez', 'Rodríguez', 'Participante'),
('Beatriz', 'Hernández', 'Pérez', 'Artista'),
('Miguel', 'Álvarez', 'Ramírez', 'Participante'),
('Claudia', 'Gómez', 'Torres', 'Artista'),
('José', 'Mora', 'García', 'Participante'),
('Antonio', 'García', 'Pérez', 'Artista'),
('Felipe', 'González', 'López', 'Participante'),
('Natalia', 'Vargas', 'Morales', 'Artista'),
('Carlos', 'Hernández', 'Ramírez', 'Participante'),
('Elena', 'Sánchez', 'González', 'Artista');
INSERT INTO persona (nombre, apellido1, apellido2, tipo) VALUES
('Sofía', 'Ruiz', 'López', 'Participante'),
('Daniel', 'Castro', 'Martínez', 'Artista'),
('Valeria', 'García', 'Fernández', 'Participante'),
('Alejandro', 'Pérez', 'Vargas', 'Artista'),
('Camila', 'Sánchez', 'Mora', 'Participante'),
('Mateo', 'Torres', 'Jiménez', 'Artista'),
('Martina', 'Díaz', 'González', 'Participante'),
('Sebastián', 'Fernández', 'Ruiz', 'Artista'),
('Luciana', 'Vargas', 'Castro', 'Participante'),
('Nicolás', 'Martínez', 'Pérez', 'Artista'),
('Emilia', 'Morales', 'Sánchez', 'Participante'),
('Gabriel', 'Jiménez', 'Torres', 'Artista'),
('Agustina', 'Gómez', 'Díaz', 'Participante'),
('Benjamín', 'Ruiz', 'Fernández', 'Artista'),
('Valentina', 'Pérez', 'Vargas', 'Participante'),
('Joaquín', 'Sánchez', 'Mora', 'Artista'),
('Florencia', 'Torres', 'Jiménez', 'Participante'),
('Thiago', 'Díaz', 'González', 'Artista'),
('Antonella', 'Fernández', 'Ruiz', 'Participante'),
('Maximiliano', 'Vargas', 'Castro', 'Artista'),
('Renata', 'Martínez', 'Pérez', 'Participante'),
('Santino', 'Morales', 'Sánchez', 'Artista'),
('Catalina', 'Jiménez', 'Torres', 'Participante'),
('Bautista', 'Gómez', 'Díaz', 'Artista'),
('Victoria', 'Ruiz', 'Fernández', 'Participante'),
('Lorenzo', 'Pérez', 'Vargas', 'Artista'),
('Abril', 'Sánchez', 'Mora', 'Participante'),
('Jerónimo', 'Torres', 'Jiménez', 'Artista'),
('Constanza', 'Díaz', 'González', 'Participante'),
('Salvador', 'Fernández', 'Ruiz', 'Artista'),
('Olivia', 'Vargas', 'Castro', 'Participante'),
('Benicio', 'Martínez', 'Pérez', 'Artista'),
('Mía', 'Morales', 'Sánchez', 'Participante'),
('Felipe', 'Jiménez', 'Torres', 'Artista'),
('Emma', 'Gómez', 'Díaz', 'Participante'),
('Bruno', 'Ruiz', 'Fernández', 'Artista'),
('Isabella', 'Pérez', 'Vargas', 'Participante'),
('Lautaro', 'Sánchez', 'Mora', 'Artista'),
('Sofía', 'Torres', 'Jiménez', 'Participante'),
('Mateo', 'Díaz', 'González', 'Artista'),
('Agustín', 'Fernández', 'Ruiz', 'Participante'),
('Martina', 'Vargas', 'Castro', 'Artista'),
('Lucas', 'Martínez', 'Pérez', 'Participante'),
('Emilia', 'Morales', 'Sánchez', 'Artista'),
('Benjamín', 'Jiménez', 'Torres', 'Participante'),
('Valentina', 'Gómez', 'Díaz', 'Artista'),
('Joaquín', 'Ruiz', 'Fernández', 'Participante'),
('Catalina', 'Pérez', 'Vargas', 'Artista'),
('Thiago', 'Sánchez', 'Mora', 'Participante');
INSERT INTO artista (id_persona, fotografia, obra_destacada) VALUES
(1, 'artista1.jpg', 'Obra A'),
(2, 'artista2.jpg', 'Obra B'),
(3, 'artista3.jpg', 'Obra C'),
(4, 'artista4.jpg', 'Obra D'),
(5, 'artista5.jpg', 'Obra E'),
(6, 'artista6.jpg', 'Obra F'),
(7, 'artista7.jpg', 'Obra G'),
(8, 'artista8.jpg', 'Obra H'),
(9, 'artista9.jpg', 'Obra I'),
(10, 'artista10.jpg', 'Obra J'),
(11, 'artista11.jpg', 'Obra K'),
(12, 'artista12.jpg', 'Obra L'),
(13, 'artista13.jpg', 'Obra M'),
(14, 'artista14.jpg', 'Obra N'),
(15, 'artista15.jpg', 'Obra O'),
(16, 'artista16.jpg', 'Obra P'),
(17, 'artista17.jpg', 'Obra Q'),
(18, 'artista18.jpg', 'Obra R'),
(19, 'artista19.jpg', 'Obra S'),
(20, 'artista20.jpg', 'Obra T'),
(21, 'artista21.jpg', 'Obra U'),
(22, 'artista22.jpg', 'Obra V'),
(23, 'artista23.jpg', 'Obra W'),
(24, 'artista24.jpg', 'Obra X'),
(25, 'artista25.jpg', 'Obra Y'),
(26, 'artista26.jpg', 'Obra Z'),
(27, 'artista27.jpg', 'Obra AA'),
(28, 'artista28.jpg', 'Obra AB'),
(29, 'artista29.jpg', 'Obra AC'),
(30, 'artista30.jpg', 'Obra AD'),
(31, 'artista31.jpg', 'Obra AE'),
(32, 'artista32.jpg', 'Obra AF'),
(33, 'artista33.jpg', 'Obra AG'),
(34, 'artista34.jpg', 'Obra AH'),
(35, 'artista35.jpg', 'Obra AI'),
(36, 'artista36.jpg', 'Obra AJ'),
(37, 'artista37.jpg', 'Obra AK'),
(38, 'artista38.jpg', 'Obra AL'),
(39, 'artista39.jpg', 'Obra AM'),
(40, 'artista40.jpg', 'Obra AN'),
(41, 'artista41.jpg', 'Obra AO'),
(42, 'artista42.jpg', 'Obra AP'),
(43, 'artista43.jpg', 'Obra AQ'),
(44, 'artista44.jpg', 'Obra AR'),
(45, 'artista45.jpg', 'Obra AS'),
(46, 'artista46.jpg', 'Obra AT'),
(47, 'artista47.jpg', 'Obra AU'),
(48, 'artista48.jpg', 'Obra AV'),
(49, 'artista49.jpg', 'Obra AW'),
(50, 'artista50.jpg', 'Obra AX');

INSERT INTO participante (id_persona, email) VALUES
(51, 'carlos.hernandez@email.com'),
(52, 'elena.sanchez@email.com'),
(53, 'david.rodriguez@email.com'),
(54, 'lucia.fernandez@email.com'),
(55, 'javier.sanchez@email.com'),
(56, 'raquel.torres@email.com'),
(57, 'francisco.gonzalez@email.com'),
(58, 'sandra.mora@email.com'),
(59, 'jorge.jimenez@email.com'),
(60, 'carmen.vargas@email.com'),
(61, 'antonio.gomez@email.com'),
(62, 'patricia.martinez@email.com'),
(63, 'carlos.martin@email.com'),
(64, 'ingrid.gonzalez@email.com'),
(65, 'raul.vazquez@email.com'),
(66, 'lidia.lopez@email.com'),
(67, 'ramon.perez@email.com'),
(68, 'marta.garcia@email.com'),
(69, 'manuel.jimenez@email.com'),
(70, 'veronica.moreno@email.com'),
(71, 'sergio.torres@email.com'),
(72, 'silvia.alvarez@email.com'),
(73, 'raul.sanchez@email.com'),
(74, 'isabel.martinez@email.com'),
(75, 'pablo.vazquez@email.com'),
(76, 'beatriz.hernandez@email.com'),
(77, 'miguel.alvarez@email.com'),
(78, 'claudia.gomez@email.com'),
(79, 'jose.mora@email.com'),
(80, 'felipe.gonzalez@email.com'),
(81, 'carlos.hernandez2@email.com'),
(82, 'elena.sanchez2@email.com'),
(83, 'david.rodriguez2@email.com'),
(84, 'lucia.fernandez2@email.com'),
(85, 'javier.sanchez2@email.com'),
(86, 'raquel.torres2@email.com'),
(87, 'francisco.gonzalez2@email.com'),
(88, 'sandra.mora2@email.com'),
(89, 'jorge.jimenez2@email.com'),
(90, 'carmen.vargas2@email.com'),
(91, 'antonio.gomez2@email.com'),
(92, 'patricia.martinez2@email.com'),
(93, 'carlos.martin2@email.com'),
(94, 'ingrid.gonzalez2@email.com'),
(95, 'raul.vazquez2@email.com'),
(96, 'lidia.lopez2@email.com'),
(97, 'ramon.perez2@email.com'),
(98, 'marta.garcia2@email.com'),
(99, 'manuel.jimenez2@email.com'),
(100, 'veronica.moreno2@email.com');